name: "model_b_acon_cpu"
backend: "openvino"
max_batch_size: 16

dynamic_batching {
  preferred_batch_size: [ 4, 8, 16 ]
  max_queue_delay_microseconds: 250
}

input [
  {
    name: "input_vector"
    data_type: TYPE_FP32
    dims: [ 14 ]
  }
]

output [
  {
    name: "output_prediction"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]

parameters: { key: "NUM_STREAMS" value: { string_value: "1" } }
parameters: { key: "INFERENCE_NUM_THREADS" value: { string_value: "1" } }
parameters: { key: "ENABLE_BATCH_PADDING" value: { string_value: "YES" } }
