import os
import matplotlib.pyplot as plt
import pandas as pd

# Load CSV output generated by perf_analyzer
csv_file = "sla_benchmark_results.csv"

if not os.path.exists(csv_file):
    print(f"Error: '{csv_file}' not found. Run perf_analyzer first.")
    exit(1)

df = pd.read_csv(csv_file)

# Normalize column headers (strip whitespace)
df.columns = df.columns.str.strip()

# Detect Concurrency, Throughput (FPS), and P99 Latency columns dynamically
concurrency_col = [col for col in df.columns if "concurrency" in col.lower()][0]
fps_col = [col for col in df.columns if any(k in col.lower() for k in ["throughput", "infer", "fps"])][0]
p99_col = [col for col in df.columns if "p99" in col.lower()][0]

# perf_analyzer outputs latency in microseconds (usec); convert to milliseconds (ms)
if "usec" in p99_col.lower() or df[p99_col].mean() > 500:
    df["p99_ms"] = df[p99_col] / 1000.0
else:
    df["p99_ms"] = df[p99_col]

# Sort sequentially by concurrency level
df = df.sort_values(by=concurrency_col)

# Create figure and primary axis (Left Y-Axis: Throughput)
fig, ax1 = plt.subplots(figsize=(10, 6), dpi=120)

color_fps = "#1f77b4"  # Blue
ax1.set_xlabel("Concurrency Level (c)", fontsize=11, fontweight="bold")
ax1.set_ylabel("Throughput (FPS / Inferences per sec)", color=color_fps, fontsize=11, fontweight="bold")
line1 = ax1.plot(
    df[concurrency_col],
    df[fps_col],
    color=color_fps,
    marker="s",
    linewidth=2.5,
    label="Throughput (FPS)",
)
ax1.tick_params(axis="y", labelcolor=color_fps)
ax1.grid(True, linestyle=":", alpha=0.6)

# Create secondary axis sharing the same X-axis (Right Y-Axis: P99 Latency)
ax2 = ax1.twinx()

color_p99 = "#d62728"  # Red
ax2.set_ylabel("P99 Latency (ms)", color=color_p99, fontsize=11, fontweight="bold")
line2 = ax2.plot(
    df[concurrency_col],
    df["p99_ms"],
    color=color_p99,
    marker="o",
    linewidth=2.5,
    linestyle="--",
    label="P99 Latency",
)
ax2.tick_params(axis="y", labelcolor=color_p99)

# SLA Limit visual marker (50 ms) on latency axis
sla_limit = 50.0
ax2.axhline(
    y=sla_limit,
    color="#7f7f7f",
    linestyle=":",
    linewidth=1.5,
    alpha=0.8,
)
ax2.text(
    df[concurrency_col].iloc[0],
    sla_limit + 1.5,
    f"SLA Limit ({sla_limit:.0f} ms)",
    color="#555555",
    fontsize=9,
    fontweight="bold",
)

# Combine legends from both axes
lines = line1 + line2
labels = [l.get_label() for l in lines]
ax1.legend(lines, labels, loc="upper left", fontsize=10)

# Title and tick adjustments
plt.title(
    "vector_vision_general_v1 — Throughput vs P99 Latency",
    fontsize=13,
    fontweight="bold",
    pad=15,
)
ax1.set_xticks(df[concurrency_col])
fig.tight_layout()

# Save dual-axis plot
output_plot = "throughput_vs_latency_dual_axis.png"
plt.savefig(output_plot, dpi=300)
print(f"Dual-axis benchmark plot saved to: {output_plot}")
plt.show()