name: "ccvnn_hardswish_12d"
platform: "onnxruntime_onnx"
max_batch_size: 64

input [
  {
    name: "input_vector"
    data_type: TYPE_FP32
    dims: [ 12 ]
  }
]

output [
  {
    name: "output_prediction"
    data_type: TYPE_FP32
    dims: [ 1 ]
  }
]

# Enable Dynamic Batching
dynamic_batching {
  max_queue_delay_microseconds: 2000
  preferred_batch_size: [ 8, 16, 32 ]
}

# Optimize CPU instance threads
instance_group [
  {
    count: 2
    kind: KIND_CPU
  }
]
optimization {
  execution_accelerators {
    gpu_execution_accelerator : [
      {
        name : "tensorrt"
        parameters { key: "precision_mode" value: "INT8" }
      }
    ]
  }
}