FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip \
    pip install -r requirements.txt

COPY watcher /app/watcher
COPY config /app/config

ENV PYTHONPATH=/app

CMD ["python3", "-m", "watcher.src.WatcherEngine"]