name: "ccvnn"
backend: "tensorrt"
max_batch_size: 0

input [
  {
    name: "input_tokens"
    data_type: TYPE_FP16
    dims: [ -1, 9 ]
  }
]

output [
  {
    name: "logits"
    data_type: TYPE_FP16
    dims: [ -1, 2 ]
  },
  {
    name: "subpixel_coords"
    data_type: TYPE_FP16
    dims: [ -1, 2 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
  }
]

optimization {
  cuda {
    graphs: true
  }
}
