apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "ccvnn-microservice.name" . }}-autoscaler
  labels:
    {{- include "ccvnn-microservice.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ccvnn-microservice.name" . }}
  minReplicaCount: 1
  maxReplicaCount: 5
  cooldownPeriod: 300
  pollingInterval: 15
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Percent
              value: 10
              periodSeconds: 60
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        metricName: triton_queue_latency_us
        query: |
          sum(rate(nv_inference_queue_duration_us[1m])) / sum(rate(nv_inference_request_success_total[1m]))
        threshold: '5000'
